# Change these first
owner: bassagap # Your GitHub organization or username, where this repository lives
repo: testingfantasy-monitor # The name of this repository

sites:
  - name: LOTR SUT Health
    url: https://lotr.testingfantasy.com/api/health
    ignoreSSL: true
    __dangerous__disable_verify_peer: true
  - name: EC2 Manager Health
    url: https://ec2-management-api-dev.testingfantasy.com/api/health
  - name: TestingFantasy Health
    url: https://www.testingfantasy.com/
  - name: Docs Testus Patronus Health
    url: https://docs-tp.testingfantasy.com/
  - name: User Assignments Testus Patronus Health
    url: https://testus-patronus.testingfantasy.com/
    
status-website:
  name: TestingFantasy Status
  cname: status.testingfantasy.com # Custom CNAME   
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
